---
label: Base
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
  description: Blog title
- name: excerpt
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Excerpt
  description: Short version of the blog content
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  hidden: true
  default: now
pages:
- _blog/happy-1k-follows.md
- _blog/mint-2-10-giveaway-winners.md
