---
label: Base
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
  description: Blog title
- name: excerpt
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Excerpt
  description: Short version of the blog content
pages:
- blog/sample-blog.md
